-- AlterTable
ALTER TABLE "ScoreAnswer" ALTER COLUMN "finalScore" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "aiScore" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "ruleScore" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "ScoreSetting" ALTER COLUMN "score" SET DATA TYPE DOUBLE PRECISION;
