@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@username = admin
@password = admin
@Content-Type = application/json

### Login
# @name login
@authToken = {{login.response.body.data.token}}
POST {{host}}/auth/login
Content-Type: {{Content-Type}}

{
  "username": "{{username}}",
  "password": "{{password}}"
}

### Start Interview
# @name startInterview
@interviewId = {{startInterview.response.body.data.id}}

POST {{host}}/interviews
Authorization: Bearer {{authToken}}
Content-Type: {{Content-Type}}

{
  "companyId": 1,
  "positionId": 1
}

### Get Current Question (INTRO)
# @name current1
GET {{host}}/interviews/{{interviewId}}/current
Authorization: Bearer {{authToken}}

### Submit Answer 1
POST {{host}}/interviews/{{interviewId}}/answers
Authorization: Bearer {{authToken}}
Content-Type: {{Content-Type}}

{
  "answer": "Perkenalkan saya adalah backend developer dengan pengalaman 3 tahun."
}

### Get Current Question (GENERAL)
# @name current2
GET {{host}}/interviews/{{interviewId}}/current
Authorization: Bearer {{authToken}}

### Submit Answer 2
POST {{host}}/interviews/{{interviewId}}/answers
Authorization: Bearer {{authToken}}
Content-Type: {{Content-Type}}

{
  "answer": "Saya tertarik dengan perusahaan ini karena fokus pada inovasi teknologi..."
}

### Get Current Question (SOFTSKILL)
# @name current3
GET {{host}}/interviews/{{interviewId}}/current
Authorization: Bearer {{authToken}}

### Submit Answer 3
POST {{host}}/interviews/{{interviewId}}/answers
Authorization: Bearer {{authToken}}
Content-Type: {{Content-Type}}

{
  "answer": "Saya cukup cepat dalam menyesuaikan diri dengan rekan kerja"
}

### Get Current Question
GET {{host}}/interviews/{{interviewId}}/current
Authorization: Bearer {{authToken}}

### Submit Answer 4
POST {{host}}/interviews/{{interviewId}}/answers
Authorization: Bearer {{authToken}}
Content-Type: {{Content-Type}}

{
  "answer": "Ya, saya pernah menggunakan JavaScript untuk membangun REST API dengan Node.js dan Express."
}

### (ULANGI SAMPAI SELESAI - TOTAL 10 SOAL)

### Get Current (Should be NULL if finished)
GET {{host}}/interviews/{{interviewId}}/current
Authorization: Bearer {{authToken}}

### Get Result
GET {{host}}/interviews/{{interviewId}}/result
Authorization: Bearer {{authToken}}